compile: *.java
    javac -cp ./HTMLparser.java:./CSVparser.java:../lib/guava-16.0.1.jar:../lib/jsoup-1.7.3.jar:./Merger.java:../lib/commons-io-2.4.jar:../lib/opencsv-2.3.jar:. RecordMerger.java
run:
    java -cp ./HTMLparser.java:./CSVparser.java:../lib/guava-16.0.1.jar:../lib/jsoup-1.7.3.jar:./Merger.java:../lib/commons-io-2.4.jar:../lib/opencsv-2.3.jar:. RecordMerger ../data/first.html ../data/second.csv